trigger:
- main

stages:
- stage: Terraform_Deploy
  displayName: Deploy Terraform
  jobs:
  - job: Terraform
    displayName: Terraform Deployment
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self  # Fetches the code from your GitHub repository

    - task: UseTerraformCLI@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - script: terraform init
      displayName: Terraform Init

    - script: terraform validate
      displayName: Terraform Validate

    - script: terraform plan -out=tfplan
      displayName: Terraform Plan
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    - script: terraform apply -auto-approve tfplan
      displayName: Terraform Apply
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
