trigger:
- main

stages:
- stage: Terraform_Deploy
  displayName: Deploy Terraform
  jobs:
  - job: Terraform
    displayName: Terraform Deployment
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self  # Fetches the code from your GitHub repository

    # Install Terraform using a script
    - script: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
        apt-get update && apt-get install -y terraform
      displayName: Install Terraform

    - script: terraform init
      displayName: Terraform Init

    - script: terraform validate
      displayName: Terraform Validate

    - script: terraform plan -out=tfplan
      displayName: Terraform Plan
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

