name: Execute Terraform

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

env:
  TF_VERSION: '1.5.7' # Specify the Terraform version
  WORKING_DIRECTORY: './' # Path to your Terraform scripts

jobs:
  terraform:
    name: Run Terraform Scripts
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # Optional: For Terraform Cloud users

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIRECTORY }}

      # Validate Terraform scripts
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIRECTORY }}

      # Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          TF_VAR_example_var: ${{ secrets.EXAMPLE_VAR }} # Optional: Pass sensitive variables

      # Apply Terraform (only on push)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.WORKING_DIRECTORY }}
